# Generated by Django 2.1.5 on 2019-02-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('level', models.IntegerField(default=1)),
                ('description', models.TextField(null=True)),
                ('size', models.CharField(max_length=30)),
                ('monster_type', models.CharField(max_length=30)),
                ('alignment', models.CharField(max_length=30)),
                ('speed', models.CharField(max_length=30)),
                ('hitpoints', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
            ],
        ),
    ]
