# Generated by Django 2.1.5 on 2019-02-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(max_length=30)),
                ('ac', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('ability', models.IntegerField()),
                ('dice_count', models.IntegerField()),
                ('dice_type', models.IntegerField()),
                ('damage_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('size', models.CharField(max_length=30)),
                ('monster_type', models.CharField(max_length=30)),
                ('alignment', models.CharField(max_length=30)),
                ('speed', models.CharField(max_length=30)),
                ('hitpoints', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('armor', models.ForeignKey(null=True, on_delete='NULL', to='encounter.Armor')),
            ],
        ),
        migrations.AddField(
            model_name='attack',
            name='owners',
            field=models.ManyToManyField(to='encounter.Character'),
        ),
    ]
