# Generated by Django 2.1.5 on 2019-02-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounter', '0002_character_armor'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
