# Generated by Django 2.1.5 on 2019-02-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('gold_reward', models.IntegerField(default=0)),
                ('exp_reward', models.IntegerField(default=0)),
                ('loot', models.TextField()),
                ('adventure', models.ForeignKey(on_delete='cascade', to='quests.Adventure')),
            ],
        ),
    ]
