# Generated by Django 2.1.5 on 2019-02-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='bluetext',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='combat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='traps',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='loot',
            field=models.TextField(null=True),
        ),
    ]
