# Generated by Django 2.1.5 on 2019-02-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_auto_20190208_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='bluetext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='combat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='loot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='traps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
