# Generated by Django 2.1.5 on 2019-02-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(max_length=30)),
                ('base_ac', models.IntegerField(max_length=30)),
                ('cost', models.IntegerField()),
                ('stealth_disadvantage', models.BooleanField()),
                ('str_minimum', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('magical_bonus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_count', models.IntegerField()),
                ('dice_value', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('ability', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('magical_bonus', models.IntegerField(default=0)),
                ('owners', models.ManyToManyField(to='encounter.Character')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('owners', models.ManyToManyField(related_name='properties', to='equipment.Weapon')),
            ],
        ),
        migrations.AddField(
            model_name='damage',
            name='owners',
            field=models.ManyToManyField(related_name='damages', to='equipment.Weapon'),
        ),
    ]
