# Generated by Django 2.1.5 on 2019-02-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20190207_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventuringGear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
